package br.com.fabioalvaro.poc_dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "cores_tabela")
public class Cor {

    private String codigo;
    private String nome;

    @DynamoDBHashKey(attributeName = "codigo")
    @DynamoDBAutoGeneratedKey
    public String getCodigo() { return codigo; }
    public void setCodigo(String codigo) { this.codigo = codigo; }

    @DynamoDBAttribute(attributeName = "nome")
    public String getNome() { return nome; }
    public void setNome(String nome) { this.nome = nome; }
}